config/routes.rb
Rails.application.routes.draw do
  get "games/matchpage" => "games#matchpage"
  get "games/profile"   => "games#profile"
  resources :games
  resources :users
  get "users/index"
  root 'users#index'

  get 'auth/steam', as: 'steam_login'
  get 'auth/:provide/callback' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'game/display_recent_games'

  get 'game/find_match'

  get 'sessions/create'

  post 'games/matchpage' => 'ratings#create', as:'rating_create'

  get 'ratings/your_rating'

  get 'user/rate'

  post 'auth/steam/callback' => 'users#auth_callback'

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings/new
  def new
    @rating = UserRating.new
  end

  def create
    @rating = UserRating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to games_path, notice: 'Thanks for rating!' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rating_params
    params.require(:post).permit(:rating, :user_id, :rating_user_id)
  end

  # #Define rating + and -
  # def upvote_count
  #   :rating += 1
  # end
  #
  # def downvote_count
  #   :rating -= 1
  # end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating, :as => :post, :url => rating_create_path(@rating)) do |f| %>
 <h3>Rate this user</h3>
   <%= f.hidden_field :user_id, :value => current_user.id %>
   <%= f.hidden_field :rating_user_id, :value => @chosen_match[:user][:id] %>
 <div class="field">
<ul id="ratings">
  <li>
    </label>
    <label id="bad" for="post-rating_-1">
      <%= f.radio_button(:rating, -1) %>
      <span class="glyphicon glyphicon-thumbs-down"></span>
    </label>
  </li>
   <li>
     <label id="good" for="post-rating_1">
       <%= f.radio_button(:rating, 1) %>
       <span class="glyphicon glyphicon-thumbs-up"><%#=  class: 'thumb' %></span>
   </li>
 </ul>

 </div>

 <div class="actions">
   <%= f.submit "Rate", :class => 'ghost-button' %>
 </div>
<% end %>