config/routes.rb
Rails.application.routes.draw do
  get "games/matchpage" => "games#matchpage"
  get "games/profile"   => "games#profile"
  resources :games
  resources :users
  get "users/index"
  root 'users#index'

  get 'auth/steam', as: 'steam_login'
  get 'auth/:provide/callback' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'game/display_recent_games'

  get 'game/find_match'

  get 'sessions/create'

  post 'games/matchpage' => 'ratings#create', as:'rating_create'

  get 'ratings/your_rating'

  get 'user/rate'

  post 'auth/steam/callback' => 'users#auth_callback'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.where(user_id: session[:user_id])
    current_user_id = current_user.id
    @current_user_rating = UserRating.find_by(user_id:current_user_id).rating
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def matchpage
    # @users = User.games.where(appid: params[:id]
    # Empty array of @games.
    @games = []
    # Iterating through all the user
    User.all.each do |user|
      # Moves to next iteration if current user session equals the user uid.
      next if session[:current_user]['uid'] == user.uid
      # find_by will return the game if it finds it. If not, returns nil. By appid.
      game = user.games.find_by(appid: params[:id])
      # User from current iteration is added alongside the game into games array as a hash.
      # If game not found, it is nil. It will break the iteration and resume iteration.
      @games << {user: user, game: game} if game != nil
      # @chosen_match = @games.sample means that the randomly selected match will be assigned as '@chosen_match' and from
      # it all of the details of the match will be displayed
      @chosen_match = @games.sample

    end

    # if the loop does not have any inputs in the array. It will redirect to index.
    # And display a notice.
    if @games.empty?
      flash[:notice] = "No one has that game. Try another one!"
      redirect_to games_path
      return
    end

    @matchedUserGames = @chosen_match[:user][:id]
    @DisplayMatchedUserGames = User.find_by(id:@matchedUserGames)


    @rating = UserRating.new

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find_by(appid:params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:game_name, :appid, :playtime, :img_icon_url, :user_id)
  end


end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_name %><br>
    <%= f.text_field :game_name %>
  </div>
  <div class="field">
    <%= f.label :appid %><br>
    <%= f.text_field :appid %>
  </div>
  <div class="field">
    <%= f.label :playtime %><br>
    <%= f.text_field :playtime %>
  </div>
  <div class="field">
    <%= f.label :img_icon_url %><br>
    <%= f.text_field :img_icon_url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<body class="findgamebody">
  <center>
    <h1 class="recenttitle animated slideInDown" style="">Find Match</h1>
    <center><h2 class="notice animated bounce"><%= notice %></h2></center>
  </center>
​
​
​
  <div class="recentgames">


    <div class="column-container">
      <div class="usercolumn col-lg-6 animated slideInLeft" style=" float:left; width:45%; height: auto;">
        <div class="row usercontent" style="padding-bottom: 10px">

        <h1 id="welcome-user">&nbsp;&nbsp;&nbsp;Welcome <%= current_user.nickname %>
            </div>
        </h1>


        <!-- <div class="col-lg-3" style="text-align:center; top: 25px;">
            <span><%= image_tag session[:current_user]["image"] %></span>
        </div> -->
        <div class="col-lg-12" style="">
          <hr>
            <div class="user-image" style="text-align:center; top: 25px;">
                <span><%= image_tag session[:current_user]["image"] %></span>
            </div>
            <!-- <br><p>Your current nickname is </p> -->
            <!-- <h2 style="text-align:center"><%= current_user.nickname %></h2> -->
            <div class="button-wrapper" style="">
              <%= link_to "Your Profile", session[:current_user]["profileurl"], class: "ghost-button" %>
            </div>
​
            <h4 class="no-margin-bottom no-margin-top" style=" text-align:center;">Rating: <span class="rating"><%= @current_user_rating %></span></h4>
​
​
              <h4 class="no-margin-top" style="text-align:center"><strong>Your recently played games: </strong></h4>
              <div class="recent-games-sidebyside" style="text-align:center" >
              <% @games.each do |game| %>
                <img src="http://media.steampowered.com/steamcommunity/public/images/apps/<%= game.appid %>/<%= game.img_icon_url %>.jpg")/ style="width:50px; height:50px;"></a>
​
              <% end %>

            </div>
        </div>
​
          </div>
        </div>



        <div class="gamescolumn col-lg-6 animated slideInRight" style="float: right; width: 45%; height: auto;">
          <h1 style="text-align: center; margin-bottom: 0">
            Select a Game
          </h1>
          <!-- <div class="row"> -->
​
​
            <% @games.each do |game| %>
            <div class="col-lg-12" style="text-align:center;">
                <hr>
                <div class="col-lg-4 img-position" style="">
                  <img src="http://media.steampowered.com/steamcommunity/public/images/apps/<%= game.appid %>/<%= game.img_icon_url %>.jpg")/ style="width:50px; height:50px;"></a>
                </div>
                <div class="col-lg-8" style="margin-bottom:10px; ">
                  <h2 class="game-header"><%= game.game_name %></h3>
                  <p class="playtime"><%= game.playtime.to_i/60 %> hours in this game</p>
                  <!--In order to display the game's icon, the 'appid' and the 'img_icon_url' were inserted inside a template steam url  -->
                  <div class="button-wrapper" style="">
                    <%= link_to "Find #{game.game_name} players",{controller: "games", action: "matchpage", id: game.appid}, class: "ghost-button", style: "width: 200px;" %>
                  </div>
                </div>
            </div>
            <% end %>
          <!-- </div> -->
        </div>
      </div>
​
​
    </div>
  </div>
​
</body>

app/views/games/matchpage.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Found a Match</title>
​
</head>

<script>
  $(document).ready(function()  {
  $('.glyphicon-thumbs-up').click(function() {
    $('.glyphicon.glyphicon-thumbs-down').css({'color':'white'});
    $(this).css({'color':'green'});
  });
  $('.glyphicon-thumbs-down').click(function() {
    $('.glyphicon.glyphicon-thumbs-up').css({'color':'white'});
    $(this).css({'color':'red'});
  });
});
</script>
<body class="matchPageBody">
​
​
​
  <div class="match animated slideInDown">
​
    <br>
​
    <h1 style="text-align:center">Meet <%= @chosen_match[:user][:nickname] %>!</h1>
    <hr>
​
    <div class="row">
      <div class="col-lg-12" style="text-align:center; padding: 0 75px;">
        <div class="user-image" style="text-align:center; top: 25px;">

            <span><img src="<%= @chosen_match[:user][:user_image] %>"</span>
        </div>
          <div class="col-lg-12">
        ​    <h3 class="" style="margin-top:0"><%= @chosen_match[:user][:name] %></h3>
            <h4>from <%= @chosen_match[:user][:user_location] %></h4>
          </div>
          <div class="button-wrapper match-profile-button">
  ​           <%= link_to @chosen_match[:user][:user_profile], :target => "_blank", class: 'thelink ghost-button' do %>
                <%= @chosen_match[:user][:nickname] %>'s Profile
  ​
             <% end %>
          </div>

        <div class="gameList">
​          <h4 class="no-margin-top" style="text-align:center"><strong>They've also recently played </strong></h4>
          <% @DisplayMatchedUserGames.games.map do |n| %>
​
          <a href="http://store.steampowered.com/app/<%= n.appid %>"><img src="http://media.steampowered.com/steamcommunity/public/images/apps/<%= n.appid %>/<%= n.img_icon_url %>.jpg ")/ style="width:50px; height:50px;" ></a>
​
          <% end %>

​
          <h4><%#= @games.sample %></h4>
          <%# byebug %>
        </div>
      </div>
      <div class="col-lg-12" style="">
        <!-- display matched user details-->

​
​
          <!-- display matched user details-->
​

            <%= render :partial => "ratings/form" %>
​
        <!-- user-image should have an assigned size -->
        <h4><%= @chosen_match[:user][:rating]%></h4>
​
        <h4><%= @chosen_match[:user][:games] %></h4>
      </div>
      <br>
    </center>
  </div>
</div>
​
​
</div>
</body>
​
​
​
</html>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
  </head>
  <body>

    <div class="title animated bounceInDown">
        <p>

          <div class="animated bounceInRight"id="profileAvatar">



        <% if current_user %>
          <br><h1>Meet <%= current_user.nickname %> !</h1>
        <%= image_tag session[:current_user]["image"] %>
        </div>
        <br>

        <% end %><center>
          <%= current_user.nickname %> also owns

    </center>

      </div>
    </div>









  </body>
</html>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game name:</strong>
  <%= @game.game_name %>
</p>

<p>
  <strong>Appid:</strong>
  <%= @game.appid %>
</p>

<p>
  <strong>Playtime:</strong>
  <%= @game.playtime %>
</p>

<p>
  <strong>Img icon url:</strong>
  <%= @game.img_icon_url %>
</p>

<p>
  <strong>User:</strong>
  <%= User.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>