config/routes.rb
Rails.application.routes.draw do
  get "games/matchpage" => "games#matchpage"
  get "games/profile"   => "games#profile"
  resources :games
  resources :users
  get "users/index"
  root 'users#index'

  get 'auth/steam', as: 'steam_login'
  get 'auth/:provide/callback' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'game/display_recent_games'

  get 'game/find_match'

  get 'sessions/create'

  post 'games/matchpage' => 'ratings#create', as:'rating_create'

  get 'ratings/your_rating'

  get 'user/rate'

  post 'auth/steam/callback' => 'users#auth_callback'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <title>Steamfriendme</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <%= google_webfonts_init ({google: ['Roboto Slab', 'Roboto']}) %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>       <!-- working properly -->
        <%= link_to "SteamFriend.me", root_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        <% unless session[:user_id].nil? %>
        <li class="animated lightSpeedIn"><%= link_to "Find Match", games_path %></li>

            <% end %>
          <li class="dropdown">

            <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li> -->
        </ul>
        <!-- <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->

        <ul class="nav navbar-nav navbar-right" id="signinoutbutton">
          <% if current_user %>
          <li><%= link_to "Sign out", logout_path %></li>
            <% else %>

          <li class="animated infinite pulse">  <%= link_to "Sign in with Steam", steam_login_path %>
          <% end %></li>


          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="spacing"> </div>

  <!-- <%= link_to image_tag("http://www.cxnteam.com/images/misc/steam_login.png"), '/auth/steam' %> -->

<%= yield %>

<!-- faq pop over -->


</body>
</html>

app/views/layouts/faq.html.erb
How does it work?
Steamfriend.me is a social networking service for PC/Linux/Mac gamers off the Steam digital distribution platform. What our application will do is match users as potential friends, 1-on-1, with other users that play similar games using user data drawn from the robust SteamAPI. Users will be matched based on the games they have on authentication already so they won’t have to input a single bit of data. After they are matched, the users are then given the option to rate their matches to improve future matches with other users.

Are you storing my information?
NO, your privacy is maitnained at all times, by signining up all you do is provide acces to your recently played games, just as you would to any other Steam user

How many games can I be matched with?
You can be matched with any game that you have in you 'recently played' game list. Currntly a mach can be made with one opponent at a time

Since you're looking at my recently played games, how far back are you looking?
We are reviewing you previously played games for the last two weeks and matching you with other players according to their recently played games

Optional: what is steam?
Steam is a multi-player platform developed by Valve Corporation. It is used to distribute games and related media online.Steam provides the user with installation and automatic management of software across multiple computers, community features such as friends lists and groups and in-game voice and chat functionality. Steam was initially developed for Microsoft Windows, they have now expanded to include a Mac OS X version and Linux, and limited functionality on the PlayStation 3 and for both iOS and Android mobile devices. In addition to being a central hub for gaming software,they have created a version of Steam with altered functionality to be used in schools for educational software. There are many single player games also available in the Steam store